version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      # connect to existing LAMP stack so PHP can access it
      - lamp_default
    ports:
      - ${POSTGRES_PORT:-5432}:5432

networks:
  lamp_default:
    external: true
